# Generated by Django 4.1.7 on 2023-05-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="address_line_1",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address_line_2",
        ),
    ]
